name: mburger
description: MBurger Dart client. You can use this package to interact with the MBurger headless CMS (https://www.mburger.cloud).
version: 2.1.6
homepage: https://web.mburger.cloud
repository: https://github.com/Mumble-SRL/MBurger-Dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.19.1
  android_id: ^0.5.0
  device_info_plus: ^12.2.0
  flutter_secure_storage: ^9.2.4
  http: ^1.6.0
  http_parser: ^4.1.2
  intl: ^0.20.2
  mime: ^2.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
